"""SQLAlchemy ORM models — the shape of the database, and nothing else.

CHECK constraints and unique indexes are declared on the models, each with an
explicit name. Exclusion constraints (no double booking, no overlapping
availability rules) cannot be autogenerated, so they live in the Alembic
migrations, where they are explicit and reviewed; see docs/database.md.

Every model module must be imported here: Alembic and the test harness read
`Base.metadata`, which only knows the models that have been imported.
"""

from app.models.availability import AvailabilityException, AvailabilityRule
from app.models.base import Base, TimestampMixin
from app.models.business_settings import BusinessSettings
from app.models.provider import Provider, ProviderService
from app.models.service import Service
from app.models.user import User, UserRole

__all__ = [
    "AvailabilityException",
    "AvailabilityRule",
    "Base",
    "BusinessSettings",
    "Provider",
    "ProviderService",
    "Service",
    "TimestampMixin",
    "User",
    "UserRole",
]
